# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "stabla"

author:
  link:             "stabla.me"
  github:           stabla
  linkedin:         gs-bonnet
  codepen:          shs
  dribbble:         stabla
  twitter:          gsbonnet
  medium:           stabla
  email:            contact@guillaumebonnet.fr

copyright:
  year:             2017
  name:             "stabla"

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "stb-blog"

# URL
url:                "http://blog.stabla.me" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop https://AWEEKJ.github.io
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Paris
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown: redcarpet
redcarpet:
  extensions:
    - lax_spacing

# Navigation
nav:
  - name:           "About"
    url:            "http://guillaumebonnet.fr"
  - name:           "Archive"
    url:            "archive"
  - name:           "Tags"
    url:            "tags"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         "images"
      type:         "pages"
    values:
      image:        true
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
